name: CI matrix tests
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  test-vitest:
    name: Test (Node ${{ inputs.node-version }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ inputs.node-version }}
      - run: pnpm test
