name: Create release PR/Publish
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for Trusted Publishing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-main:
    name: Create release PR and publish on merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          install-npm: 'true'
      # Based on https://github.com/changesets/action/issues/303#issuecomment-1888167265
      - name: Capture new release version
        run: |
          pnpm changeset version
          echo "NEW_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          git restore .
      - name: Create release PR OR Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commitMode: github-api
          title: 'chore: release v${{ env.NEW_VERSION }}'
          commit: 'chore: release v${{ env.NEW_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
